# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user2/Documents/Vivado/vga_ip_repo/constrains/base.xdc

# Block Designs: bd/definitive/definitive.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive || ORIG_REF_NAME==definitive} -quiet] -quiet

# IP: bd/definitive/ip/definitive_processing_system7_0_0/definitive_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_processing_system7_0_0 || ORIG_REF_NAME==definitive_processing_system7_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_ov7670_vga_0_0/definitive_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_ov7670_vga_0_0 || ORIG_REF_NAME==definitive_ov7670_vga_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_ov7670_controller_0_0/definitive_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_ov7670_controller_0_0 || ORIG_REF_NAME==definitive_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_debounce_0_0/definitive_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_debounce_0_0 || ORIG_REF_NAME==definitive_debounce_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_ov7670_capture_0_0/definitive_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_ov7670_capture_0_0 || ORIG_REF_NAME==definitive_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_blk_mem_gen_0_0/definitive_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_blk_mem_gen_0_0 || ORIG_REF_NAME==definitive_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_clk_wiz_0_0/definitive_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_clk_wiz_0_0 || ORIG_REF_NAME==definitive_clk_wiz_0_0} -quiet] -quiet

# IP: bd/definitive/ip/definitive_xlconstant_0_0/definitive_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==definitive_xlconstant_0_0 || ORIG_REF_NAME==definitive_xlconstant_0_0} -quiet] -quiet

# XDC: bd/definitive/definitive_ooc.xdc
